
#include <doctest/doctest.h>
#include <postalt/postalt.h>
#include <postalt/version.h>

#include <string>
#include <vector>

TEST_CASE("Postalt") {
  using namespace postalt;

  Postalt postalt("Tests");
  std::vector<std::string> l;
  l.push_back("F221	99	chr11	105017764	0	100M	=	105018042	378	TAGCAAGGCAGGCCAACATTCAGATTCAGGAAATACAGAGAATGCCACAAAGATACTCCTCGAGAAGAGCAACTCCAAGACACATAATTGTCAGATTCAC	FEF;BFFFF?FFFBEFEFEFFDFFD?FEFFFDEEFCFF?F4E9FFFFDFECFBEDFFFBFEFFFFEFEFFFFFF?FDDFFEEFFCFEFCFFEFFFDFEFF	NM:i:0	MD:Z:100	AS:i:100	XS:i:100	RG:Z:90");
  l.push_back("F221	147	chr11	105018042	0	100M	=	105017764	-378	TATCCAGCCAAACTAAGCTTCATAAGTGAAGGAGAAATAAAATACTTTACAGACAAGCAAATGCTGAGAGATTTTGTCACCACCAGGCCTGCCCTAAAAG	FEEFFEFFEFFEFEFFFFFFFFEFFFFFFFFFFEFFFFFFFFFFFFFEFFEFFFEEFFFFFFFFFFFFFFEFFFFFFFFFFFFFEFFFFFFFFFFFFFFF	NM:i:0	MD:Z:100	AS:i:100	XS:i:100	RG:Z:90");
  std::string out;
  CHECK(postalt.run(l, out));
}

TEST_CASE("Postalt version") { CHECK(std::string(POSTALT_VERSION) == std::string("1.0.0")); }
